(ns last-train.acceptance.generator
  "acceptance-entrypoint-generator <json-ir> <generated-test-output>
  Writes a Speclj entry point that embeds the IR and runs every scenario
  execution through the acceptance runtime, plus per-feature metadata."
  (:require [cheshire.core :as json]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [last-train.acceptance.runtime :as runtime])
  (:import (java.security MessageDigest)))

(defn metadata-name [feature-path]
  (str (-> feature-path str/lower-case (str/replace #"[^a-z0-9]+" "-") (str/replace #"^-+|-+$" ""))
       ".json"))

(defn- stem [ir-path]
  (str/replace (.getName (io/file ir-path)) #"\.json$" ""))

(defn- sha256 [text]
  (let [digest (.digest (MessageDigest/getInstance "SHA-256") (.getBytes text "UTF-8"))]
    (str "sha256:" (apply str (map #(format "%02x" (bit-and % 0xff)) digest)))))

(defn- test-source [ir-path ir-json]
  (let [ir (runtime/read-ir ir-json)
        feature-stem (stem ir-path)]
    (str ";; Generated by acceptance-entrypoint-generator from " ir-path ". Do not edit.\n"
         "(ns last-train.generated." feature-stem "-spec\n"
         "  (:require [speclj.core :refer :all]\n"
         "            [last-train.acceptance.runtime :as runtime]\n"
         "            [last-train.acceptance.steps :as steps]))\n\n"
         "(def ir (runtime/read-ir " (pr-str ir-json) "))\n\n"
         "(describe " (pr-str (get ir "name")) "\n"
         (str/join "\n"
                   (for [{:keys [name scenario example-index]} (runtime/executions ir)]
                     (str "  (it " (pr-str name) "\n"
                          "    (should-be-nil (runtime/run-execution steps/handlers ir "
                          scenario " " example-index ")))")))
         ")\n")))

(defn generate
  "Map of output path -> file content for one IR file."
  [ir-path ir-json output-dir]
  (let [feature-stem (stem ir-path)
        feature-path (str "features/" feature-stem ".feature")
        test-path (str output-dir "/last_train/generated/" (str/replace feature-stem "-" "_") "_spec.clj")
        source (test-source ir-path ir-json)
        metadata {"schema_version" 1
                  "feature_path" feature-path
                  "ir_path" ir-path
                  "implementation_hash" (sha256 source)
                  "hash_scope" "generated_files"
                  "generated_files" [test-path]}]
    {test-path source
     (str output-dir "/metadata/" (metadata-name feature-path)) (str (json/generate-string metadata {:pretty true}) "\n")}))

(defn run [args]
  (if (not= 2 (count args))
    (do (binding [*out* *err*]
          (println "Usage: acceptance-entrypoint-generator <json-ir> <generated-test-output>"))
        2)
    (let [[ir-path output-dir] args]
      (try
        (doseq [[path content] (generate ir-path (slurp ir-path) output-dir)]
          (io/make-parents path)
          (spit path content))
        0
        (catch Exception e
          (binding [*out* *err*] (println "Entry point generation failed:" (ex-message e)))
          1)))))

(defn -main [& args]
  (System/exit (run args)))
